
# Update frequency the entities will be updated
entityUpdateSpeed: 50

# Skeleton's will use swords to attack the player when the player is close enough. (6 block radius)
skeletonSwordSwitch:
  enabled: true
  swordRange: 6

# Wither skeleton's will use fire bows when the player is too far for sword use. (6 block radius+)
witherSkeletonSwordSwitch:
  enabled: true
  swordRange: 5

# Make it possible for (wither) skeletons to ride (cave) spiders.
skeletonSpiderMount:
  enabled: true
  updateEntityfromPlayer: 12 # Range to look for entities to update
  mountFindRange: 4 # Range the entity will look for a mount

# Make it possible for baby zombies to ride on chickens.
zombieChickenMount:
  enabled: true
  updateEntityfromPlayer: 12 # Range to look for entities to update
  mountFindRange: 4 # Range the entity will look for a mount

# Make it possible to spawn charged creepers
chargedCreeperSpawn:
  enabled: true
  spawnChance: 100 # 1 in the given number will spawn a creeper;
  # Higher number is a lower chance

## TODO
#skeletonHorseMount: true
#fasterZombie: true
#monsterHeal: true
#ghastMachineGun: true
#enderDragonNoSitting
#enderDragonMachineGun
#enderDragonRain
#enderDragonReinforcements