# Update frequency the entities will be updated
entityUpdateSpeed: 50

# Skeleton's will use swords to attack the player when the player is close enough. (6 block radius)
skeletonSwordSwitch:
  enabled: true
  swordRange: 6

# Wither skeleton's will use fire bows when the player is too far for sword use. (6 block radius+)
witherSkeletonSwordSwitch:
  enabled: true
  swordRange: 5

# Make it possible for (wither) skeletons to ride (cave) spiders.
skeletonSpiderMount:
  enabled: true
  updateEntityfromPlayer: 12 # Range to look for entities to update
  mountFindRange: 4 # Range the entity will look for a mount

# Make it possible for baby zombies to ride on chickens.
zombieChickenMount:
  enabled: true
  updateEntityfromPlayer: 12 # Range to look for entities to update
  mountFindRange: 4 # Range the entity will look for a mount

# Make it possible to spawn charged creepers
chargedCreeperSpawn:
  enabled: true
  spawnChance: 100 # 1 in the 100 will spawn a charged creeper
  # Higher number is a lower chance
  
# Make creepers spawn with potion effects
creeperSpawnPotionEffect:
  enabled: true
  spawnChance: 50 # 1 in the 50 will spawn a creeper with a potion effect
  positiveEffects: true
  # Examples: ABSORPTION, HEALING, SPEED, STRENGTH, FIRE RESISTANCE
  negativeEffects: true
  # Examples: POISON, WITHER, BLINDNESS, SLOW DIGGING, WEAKNESS, HUNGER
  rareEffects: true
  # Examples: LEVITATION, DOLPHINS GRACE, GLOWING, LUCK, BAD_OMEN

# Turn witches into necromancers who spawn baby zombies.
# Only works at night
witchNecromancer:
  enabled: true
  cooldown: 450 # Wait before the witch could spawn zombies again.
  spawnAmount: 3 # The maximum amount of zombies could be spawn. this number is random.
  spawnRadius: 3 # The distance the zombies spawn from the witch.
  scanRadius: 10 # The distance from the player that should be checked for witches.

# Wither can spawn wither skeletons when attacked.
witherReinforcements:
  enabled: true
  cooldown: 45 # wait till a new spawn wave in seconds.
  spawnRadius: 10 # Max radius the skeletons could spawn.
  spawnChance: 10 # Chance the skeletons spawn when attacked.
  spawnAmount: 5 # Max amount of skeletons that could spawn.

# Wither can give negative effects to players close  
witherEffects:
  enabled: true
  cooldown: 30 # Wait before the attack is done again.
  spawnChance: 10 # The chance the attack will happen on attack.
  attackRadius: 7 # Max radius of the attack.
  attackDuration: 30 # Duration of the given potion effect.
  

## TODO
#skeletonHorseMount: true
#fasterZombie: true
#monsterHeal: true
#ghastMachineGun: true
#enderDragonNoSitting
#enderDragonMachineGun
#enderDragonRain
#enderDragonReinforcements