
# Skeleton's will use swords to attack the player when the player is close enough. (6 block radius)
skeletonSwordSwitch: true

# Wither skeleton's will use fire bows when the player is too far for sword use. (6 block radius+)
witherSkeletonSwordSwitch: true

# Make it possible for (wither) skeletons to ride (cave) spiders.
skeletonSpiderMount: true

# Make it possible for baby zombies to ride on chickens.
zombieChickenMount: true

## TODO
#skeletonHorseMount: true
#fasterZombie: true
#monsterHeal: true
#ghastMachineGun: true
#enderDragonNoSitting
#enderDragonMachineGun
#enderDragonRain
#enderDragonReinforcements