skeletonSwordSwitch: true
witherSkeletonSwordSwitch: true

## TODO
#skeletonSpiderMount: true
#skeletonHorseMount: true
#fasterZombie: true
#monsterHeal: true
#ghastMachineGun: true
#enderDragonNoSitting
#enderDragonMachineGun
#enderDragonRain
#enderDragonReinforcements